server:
  port: 8081
spring:
  profiles:
    active: docker
  application:
    name: order-service
  config:
    import: "optional:configserver:http://config-server:8100/"

eureka:
  instance:
    hostname: order-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS